    ...
    Long xminL = (Long)jsonObject.get("xmin");
    Long xmaxL = (Long)jsonObject.get("xmax");
    Long yminL = (Long)jsonObject.get("ymin");
    Long ymaxL = (Long)jsonObject.get("ymax");
    ...