Features features = Features.newBuilder()
    .putFeature("image/width", getIntFeature(width))
    .putFeature("image/height", getIntFeature(height))
    .putFeature("image/filename", getStringFeature(filename))
    .putFeature("image/source_id", getStringFeature(filename))
    .putFeature("image/encoded", getImageFeature(bi))
    .putFeature("image/format", getStringFeature("jpeg"))
    .putFeature("image/object/bbox/xmin", getFloatFeature(xmin))
    .putFeature("image/object/bbox/xmax", getFloatFeature(xmax))
    .putFeature("image/object/bbox/ymin", getFloatFeature(ymin))
    .putFeature("image/object/bbox/ymax", getFloatFeature(ymax))
    .putFeature("image/object/class/text", getStringListFeature(label_txt))
    .putFeature("image/object/class/label", getIntListFeature(label))
    .build();